language: scala
script:
- sbt clean coverage test scalastyle coverageReport coverageAggregate codacyCoverage
- sbt clean +update
- sbt +compile +package
- sbt +test +publish
scala:
- 2.10.4
jdk:
- oraclejdk7
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/39b434177bceb59300c7
    on_success: always
    on_failure: always
    on_start: true
env:
  global:
  - MINIBOXING_MAVEN_REALM="Sonatype Nexus Repository Manager"
  - MINIBOXING_MAVEN_DOMAIN="oss.sonatype.org"
  - secure: "YH2L0Ex1sxRZTz9+I3z5bKH6OwQa3yQ/SrDj9btf4JfXAoMkBgMXSi8/SIYzDKrkng2rmxcyocoNYcj3DHiRZxwoLO8OU6zaABh6LgtqfA+IfQTMuqyf/2Msphowgcm5biVFmBXQNIQfGf/Wpzv5F7uoz1drKtOMOTnmjkKbP60="
  - secure: "gtMP4tLkBQaoqrdahvqBYtSAMp9wWe0CRZA5oE/sen0Soww5QYOtsCGlNkzDO0LrUxL4Dsux/3Wlu2oF0/zWanadKwKpKxXMmIBhn716bbHm51L7JZdixdWEyYP7IkDXPqm1WYqAcNgDk97TFBDv9FRdX4ZeuXwg1uMyugFYJeQ="
  - secure: "E8jNPj2r4L+oDi3oxdI4kPoL5HpPw5tvIdzoRLfWhmFo0JG1Hm0U7E/B8Ms70eqiWKhE/bsF7nVtlW6xKGDy3VqnFcC3xp1TbfHvVt5DFrTd7ESJisq3sgJEoDoe/6qgC9vsVxQJIZmRxxJbV9+e2Vu5Qm3UEWyUUiDLTa/R0Rc="
branches:
  only:
  - master
  - wip
